/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package montyhall.Ui;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import montyhall.Core.Controller;
import montyhall.Core.Observer;
import montyhall.Models.Game;

/**
 * User interface of the Monty hall simulation
 * @author Wesley
 */
public class UserInterface extends javax.swing.JFrame implements Observer {

    private ButtonGroup doorGroup;
    
    /**
     * The game instance
     */
    private Game game;
    
    /**
     * The UI manager for the application
     */
    private UIManager uiManager;
    
    /**
     * The button group of radio buttons
     */
    private ButtonGroup btnGroup;
    
    /**
     * The controller of the simulation
     */
    private Controller controller;
    
    /**
     * Creates new form UserInterface
     */
    public UserInterface(Controller c) {
        initComponents();
        this.controller = c;
        this.doorGroup = new ButtonGroup();
        this.doorGroup.add(this.tbDoor1);
        this.doorGroup.add(this.tbDoor2);
        this.doorGroup.add(this.tbDoor3);
        this.btnGroup = new ButtonGroup();
        this.btnGroup.add(this.rbStrategyOne);
        this.btnGroup.add(this.rbStrategyTwo);
        this.uiManager = new UIManager();
        this.game = c.getGame();
        this.game.registerObserver(this);
    }
    
    /**
     * Gets the currently selected radio buttons text
     * @param buttonGroup takes a button group
     * @return returns the associated string
     */
    private String getSelectedStrategyText(ButtonGroup btnGroup) {
        
        //Loop through buttons
        for (Enumeration<AbstractButton> buttons = btnGroup.getElements(); buttons.hasMoreElements();) {
            
            //gets the next button
            AbstractButton button = buttons.nextElement();

            //determine if button is selected
            if (button.isSelected()) {
                
                //return the text
                return button.getText().substring(button.getText().indexOf(":")+2,button.getText().length() );
            }
        }

        return null;
    }
    
    /**
     * Gets the selected Doors value
     * @param btnGroup takes in a button group
     * @return the numeric value associated with said button
     */
    private int getSelectedDoorValue(ButtonGroup btnGroup) {
        
        //Loop through buttons
        for (Enumeration<AbstractButton> buttons = btnGroup.getElements(); buttons.hasMoreElements();) {
            
            //gets the next button
            AbstractButton button = buttons.nextElement();

            //determine if button is selected
            if (button.isSelected()) {
                
                //return the text
                return Integer.parseInt(button.getText());
            }
        }

        return -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbStrategyOne = new javax.swing.JRadioButton();
        rbStrategyTwo = new javax.swing.JRadioButton();
        slNumPlays = new javax.swing.JSlider();
        slNumPlays.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                lblNumRuns.setText(String.valueOf(slNumPlays.getValue()));
            }
        });
        lblNumPlays = new javax.swing.JLabel();
        tbDoor1 = new javax.swing.JToggleButton();
        tbDoor2 = new javax.swing.JToggleButton();
        tbDoor3 = new javax.swing.JToggleButton();
        btnStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        lblNumRuns = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbStrategyOne.setText("Strategy 1: switch");
        rbStrategyOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbStrategyOneActionPerformed(evt);
            }
        });

        rbStrategyTwo.setText("Strategy 2: stay");
        rbStrategyTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbStrategyTwoActionPerformed(evt);
            }
        });

        slNumPlays.setMaximum(500);
        slNumPlays.setMinimum(1);

        lblNumPlays.setText("Enter number of Plays");

        tbDoor1.setText("1");
        tbDoor1.setActionCommand("1");

        tbDoor2.setText("2");

        tbDoor3.setText("3");
        tbDoor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDoor3ActionPerformed(evt);
            }
        });

        btnStart.setText("start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        txtResults.setColumns(20);
        txtResults.setRows(5);
        jScrollPane1.setViewportView(txtResults);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblNumRuns.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slNumPlays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumPlays)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumRuns))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbStrategyOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbStrategyTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tbDoor1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbDoor2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbDoor3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbStrategyOne)
                            .addComponent(btnClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbStrategyTwo)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumPlays)
                            .addComponent(lblNumRuns))
                        .addGap(14, 14, 14)
                        .addComponent(slNumPlays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbDoor1)
                            .addComponent(tbDoor2)
                            .addComponent(tbDoor3))
                        .addGap(32, 32, 32)
                        .addComponent(btnStart)))
                .addGap(189, 189, 189))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Radio button that indicates that the user has chosen strategy one
     * @param evt 
     */
    private void rbStrategyOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbStrategyOneActionPerformed
        // TODO add your handling code here:
       if(this.rbStrategyOne.isSelected()){
           this.rbStrategyTwo.setSelected(false);
           this.controller.setStrategy(getSelectedStrategyText(this.btnGroup));

       }
    }//GEN-LAST:event_rbStrategyOneActionPerformed

    /**
     * Radio button that indicates that the user has chosen strategy two
     * @param evt 
     */
    private void rbStrategyTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbStrategyTwoActionPerformed
        // TODO add your handling code here:
        if(this.rbStrategyTwo.isSelected()){
           this.rbStrategyOne.setSelected(false);
           this.controller.setStrategy(getSelectedStrategyText(this.btnGroup));
       }
    }//GEN-LAST:event_rbStrategyTwoActionPerformed

    /**
     * Starts the Monty Hall simulation
     * @param evt 
     */
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        this.controller.Setup(this.slNumPlays.getValue(), getSelectedDoorValue(this.doorGroup));
        this.controller.Start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void tbDoor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDoor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDoor3ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.txtResults.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Controller controller = new Controller();
                new UserInterface(controller).setVisible(true);
                
            }
        });
        
        
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumPlays;
    private javax.swing.JLabel lblNumRuns;
    private javax.swing.JRadioButton rbStrategyOne;
    private javax.swing.JRadioButton rbStrategyTwo;
    private javax.swing.JSlider slNumPlays;
    private javax.swing.JToggleButton tbDoor1;
    private javax.swing.JToggleButton tbDoor2;
    private javax.swing.JToggleButton tbDoor3;
    private javax.swing.JTextArea txtResults;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String value) {
        this.txtResults.append(String.valueOf(value) + "\n");
    }
}




